development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: chatroom_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= Rails.application.credentials.redis[:redis_url] %>
  channel_prefix: chatroom_production
